//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace satmDebugger.satmCore {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entries", Namespace="http://schemas.datacontract.org/2004/07/satm")]
    [System.SerializableAttribute()]
    public partial class Entries : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string coreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string entryDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string core {
            get {
                return this.coreField;
            }
            set {
                if ((object.ReferenceEquals(this.coreField, value) != true)) {
                    this.coreField = value;
                    this.RaisePropertyChanged("core");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string entryDescription {
            get {
                return this.entryDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.entryDescriptionField, value) != true)) {
                    this.entryDescriptionField = value;
                    this.RaisePropertyChanged("entryDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Events", Namespace="http://schemas.datacontract.org/2004/07/satm")]
    [System.SerializableAttribute()]
    public partial class Events : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cultureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string directionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int enterCamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime enterTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string entryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int exitCamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime exitTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool legalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ownerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ttnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int upCamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime upTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string whoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carID {
            get {
                return this.carIDField;
            }
            set {
                if ((object.ReferenceEquals(this.carIDField, value) != true)) {
                    this.carIDField = value;
                    this.RaisePropertyChanged("carID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string culture {
            get {
                return this.cultureField;
            }
            set {
                if ((object.ReferenceEquals(this.cultureField, value) != true)) {
                    this.cultureField = value;
                    this.RaisePropertyChanged("culture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direction {
            get {
                return this.directionField;
            }
            set {
                if ((object.ReferenceEquals(this.directionField, value) != true)) {
                    this.directionField = value;
                    this.RaisePropertyChanged("direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                if ((this.endDateField.Equals(value) != true)) {
                    this.endDateField = value;
                    this.RaisePropertyChanged("endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int enterCam {
            get {
                return this.enterCamField;
            }
            set {
                if ((this.enterCamField.Equals(value) != true)) {
                    this.enterCamField = value;
                    this.RaisePropertyChanged("enterCam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime enterTime {
            get {
                return this.enterTimeField;
            }
            set {
                if ((this.enterTimeField.Equals(value) != true)) {
                    this.enterTimeField = value;
                    this.RaisePropertyChanged("enterTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string entry {
            get {
                return this.entryField;
            }
            set {
                if ((object.ReferenceEquals(this.entryField, value) != true)) {
                    this.entryField = value;
                    this.RaisePropertyChanged("entry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int exitCam {
            get {
                return this.exitCamField;
            }
            set {
                if ((this.exitCamField.Equals(value) != true)) {
                    this.exitCamField = value;
                    this.RaisePropertyChanged("exitCam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime exitTime {
            get {
                return this.exitTimeField;
            }
            set {
                if ((this.exitTimeField.Equals(value) != true)) {
                    this.exitTimeField = value;
                    this.RaisePropertyChanged("exitTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                if ((object.ReferenceEquals(this.ipField, value) != true)) {
                    this.ipField = value;
                    this.RaisePropertyChanged("ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool legal {
            get {
                return this.legalField;
            }
            set {
                if ((this.legalField.Equals(value) != true)) {
                    this.legalField = value;
                    this.RaisePropertyChanged("legal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                if ((object.ReferenceEquals(this.ownerField, value) != true)) {
                    this.ownerField = value;
                    this.RaisePropertyChanged("owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((this.startDateField.Equals(value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ttn {
            get {
                return this.ttnField;
            }
            set {
                if ((object.ReferenceEquals(this.ttnField, value) != true)) {
                    this.ttnField = value;
                    this.RaisePropertyChanged("ttn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                if ((object.ReferenceEquals(this.uidField, value) != true)) {
                    this.uidField = value;
                    this.RaisePropertyChanged("uid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int upCam {
            get {
                return this.upCamField;
            }
            set {
                if ((this.upCamField.Equals(value) != true)) {
                    this.upCamField = value;
                    this.RaisePropertyChanged("upCam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime upTime {
            get {
                return this.upTimeField;
            }
            set {
                if ((this.upTimeField.Equals(value) != true)) {
                    this.upTimeField = value;
                    this.RaisePropertyChanged("upTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string who {
            get {
                return this.whoField;
            }
            set {
                if ((object.ReferenceEquals(this.whoField, value) != true)) {
                    this.whoField = value;
                    this.RaisePropertyChanged("who");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cores", Namespace="http://schemas.datacontract.org/2004/07/satm")]
    [System.SerializableAttribute()]
    public partial class Cores : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="satmCore.satmICore", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface satmICore {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/satmICore/SignIn", ReplyAction="http://tempuri.org/satmICore/SignInResponse")]
        bool SignIn();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/satmICore/SignIn", ReplyAction="http://tempuri.org/satmICore/SignInResponse")]
        System.Threading.Tasks.Task<bool> SignInAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/satmICore/SignOut", ReplyAction="http://tempuri.org/satmICore/SignOutResponse")]
        bool SignOut();
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/satmICore/SignOut", ReplyAction="http://tempuri.org/satmICore/SignOutResponse")]
        System.Threading.Tasks.Task<bool> SignOutAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/satmICore/ARM", ReplyAction="http://tempuri.org/satmICore/ARMResponse")]
        string ARM();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/satmICore/ARM", ReplyAction="http://tempuri.org/satmICore/ARMResponse")]
        System.Threading.Tasks.Task<string> ARMAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/satmICore/GetEvents", ReplyAction="http://tempuri.org/satmICore/GetEventsResponse")]
        System.Collections.Generic.List<satmDebugger.satmCore.Events> GetEvents(System.Collections.Generic.List<satmDebugger.satmCore.Entries> entries, System.DateTime from, System.DateTime to, bool raw);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/satmICore/GetEvents", ReplyAction="http://tempuri.org/satmICore/GetEventsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<satmDebugger.satmCore.Events>> GetEventsAsync(System.Collections.Generic.List<satmDebugger.satmCore.Entries> entries, System.DateTime from, System.DateTime to, bool raw);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/satmICore/GetEntries", ReplyAction="http://tempuri.org/satmICore/GetEntriesResponse")]
        System.Collections.Generic.List<satmDebugger.satmCore.Entries> GetEntries();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/satmICore/GetEntries", ReplyAction="http://tempuri.org/satmICore/GetEntriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<satmDebugger.satmCore.Entries>> GetEntriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/satmICore/GetCores", ReplyAction="http://tempuri.org/satmICore/GetCoresResponse")]
        System.Collections.Generic.List<satmDebugger.satmCore.Cores> GetCores();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/satmICore/GetCores", ReplyAction="http://tempuri.org/satmICore/GetCoresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<satmDebugger.satmCore.Cores>> GetCoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/satmICore/UpdateEvent", ReplyAction="http://tempuri.org/satmICore/UpdateEventResponse")]
        void UpdateEvent(string core, string uid);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/satmICore/UpdateEvent", ReplyAction="http://tempuri.org/satmICore/UpdateEventResponse")]
        System.Threading.Tasks.Task UpdateEventAsync(string core, string uid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface satmICoreChannel : satmDebugger.satmCore.satmICore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class satmICoreClient : System.ServiceModel.ClientBase<satmDebugger.satmCore.satmICore>, satmDebugger.satmCore.satmICore {
        
        public satmICoreClient() {
        }
        
        public satmICoreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public satmICoreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public satmICoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public satmICoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SignIn() {
            return base.Channel.SignIn();
        }
        
        public System.Threading.Tasks.Task<bool> SignInAsync() {
            return base.Channel.SignInAsync();
        }
        
        public bool SignOut() {
            return base.Channel.SignOut();
        }
        
        public System.Threading.Tasks.Task<bool> SignOutAsync() {
            return base.Channel.SignOutAsync();
        }
        
        public string ARM() {
            return base.Channel.ARM();
        }
        
        public System.Threading.Tasks.Task<string> ARMAsync() {
            return base.Channel.ARMAsync();
        }
        
        public System.Collections.Generic.List<satmDebugger.satmCore.Events> GetEvents(System.Collections.Generic.List<satmDebugger.satmCore.Entries> entries, System.DateTime from, System.DateTime to, bool raw) {
            return base.Channel.GetEvents(entries, from, to, raw);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<satmDebugger.satmCore.Events>> GetEventsAsync(System.Collections.Generic.List<satmDebugger.satmCore.Entries> entries, System.DateTime from, System.DateTime to, bool raw) {
            return base.Channel.GetEventsAsync(entries, from, to, raw);
        }
        
        public System.Collections.Generic.List<satmDebugger.satmCore.Entries> GetEntries() {
            return base.Channel.GetEntries();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<satmDebugger.satmCore.Entries>> GetEntriesAsync() {
            return base.Channel.GetEntriesAsync();
        }
        
        public System.Collections.Generic.List<satmDebugger.satmCore.Cores> GetCores() {
            return base.Channel.GetCores();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<satmDebugger.satmCore.Cores>> GetCoresAsync() {
            return base.Channel.GetCoresAsync();
        }
        
        public void UpdateEvent(string core, string uid) {
            base.Channel.UpdateEvent(core, uid);
        }
        
        public System.Threading.Tasks.Task UpdateEventAsync(string core, string uid) {
            return base.Channel.UpdateEventAsync(core, uid);
        }
    }
}
