//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace satmAnalyzer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Integrated Security=True;MultipleActiveResultSets=True")]
        public string satmDB {
            get {
                return ((string)(this["satmDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"INSERT [satm].[dbo].[PROTOCOL](objtype,objid,action,date,owner,pk,processed)
select objtype,objid,action,date,owner,pk,'false' from OPENROWSET
('SQLOLEDB','Server={@SQLServer};UID={@username};PWD={@password}','SELECT [objtype]
      ,[objid],[action],[date],[owner],[pk]
  FROM [{@Database}].[dbo].[PROTOCOL] WHERE OBJTYPE=''GRAY''
  order by date desc') rdb
  where NOT EXISTS (select pk FROM [satm].[dbo].[PROTOCOL] ldb where rdb.pk=ldb.pk)")]
        public string synchrProtocol {
            get {
                return ((string)(this["synchrProtocol"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"INSERT [satm].[dbo].[satm1C] (owner,[1cID],carID,Date,Entry,Culture,WHO,pk)
select * from OPENROWSET
('SQLOLEDB','Server={@SQLServer};UID={@username};PWD={@password}','SELECT *
  FROM [{@Database}].[dbo].[PROTOCOL1C]') rdb
  where NOT EXISTS (select owner,pk FROM [satm].[dbo].[satm1C] ldb where 
  (rdb.owner=ldb.owner) and  (rdb.pk=ldb.pk) ) ")]
        public string synchrSAUP {
            get {
                return ((string)(this["synchrSAUP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int ITVDefaultDelay {
            get {
                return ((int)(this["ITVDefaultDelay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ITVMaxDelay {
            get {
                return ((int)(this["ITVMaxDelay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int ITVShootDelay {
            get {
                return ((int)(this["ITVShootDelay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\SATM\\bin\\export\\")]
        public string ImagePath {
            get {
                return ((string)(this["ImagePath"]));
            }
        }
    }
}
